spring:
    datasource:
        url: ${DB_URL:jdbc:postgresql://db:5432/michelet_db}
        username: ${DB_USERNAME:admin}
        password: ${DB_PASSWORD:admin}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
    data:
        redis:
            host: redis
            port: 6379
    kafka:
        bootstrap-servers: kafka:9092 # 도커는 컨테이너 이름(kafka)
eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
