spring:
    application:
        name: inventory-service
    profiles:
        active: local
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: true
                default_schema: inventory_service
                hbm2ddl.create_namespaces: true

server:
    port: 19900

inventory:
    retry:
        max-count: 3
    kafka:
        topic:
            product-created: "product.created"
            reserved: "stock.reserved"
            restored: "stock.restored"
